#include "core/ShaderExport.h"

#include "converter/ShaderConverter.h"

#include <array>
#include <sstream>
#include <string>

namespace acs
{

static void emitVec4(std::ostringstream& o, const char* name, const std::array<float, 4>& v)
{
    o << "    float " << name << "[4] = { " << v[0] << "f, " << v[1] << "f, " << v[2] << "f, " << v[3] << "f };\n";
}

std::string generateExtendedCppExport(const AppState& state)
{
    const ShaderConstructorConfig& c = state.m_constructor;
    std::ostringstream o;
    o << "// Auto-generated by appCreatorShader\n";
    o << "#pragma once\n\n";
    o << "#include <cstdint>\n\n";
    o << "namespace acs_export {\n\n";
    o << "struct ShaderConfig {\n";
    o << "    float bgWidth = " << c.m_bgWidth << "f;\n";
    o << "    float bgHeight = " << c.m_bgHeight << "f;\n";
    o << "    float objWidth = " << c.m_objWidth << "f;\n";
    o << "    float objHeight = " << c.m_objHeight << "f;\n";
    o << "    float objPosX = " << c.m_objPosX << "f;\n";
    o << "    float objPosY = " << c.m_objPosY << "f;\n";
    o << "    bool objPosPixelMode = " << (c.m_objPosPixelMode ? "true" : "false") << ";\n";
    o << "    float animSpeed = " << c.m_animSpeed << "f;\n";
    o << "    float timeScale = " << c.m_timeScale << "f;\n";
    emitVec4(o, "bgColor", c.m_bgColor);
    emitVec4(o, "objColor", c.m_objColor);
    emitVec4(o, "glowColor", c.m_glowColor);
    o << "    float intensity = " << c.m_intensity << "f;\n";
    o << "    float density = " << c.m_density << "f;\n";
    o << "    float noiseScale = " << c.m_noiseScale << "f;\n";
    o << "    float edgeSoftness = " << c.m_edgeSoftness << "f;\n";
    o << "    float extraWarp = " << c.m_extraWarp << "f;\n";
    o << "    bool enableFog = " << (c.m_enableFog ? "true" : "false") << ";\n";
    o << "    bool enableTrail = " << (c.m_enableTrail ? "true" : "false") << ";\n";
    o << "    bool enableGlow = " << (c.m_enableGlow ? "true" : "false") << ";\n";
    o << "    bool enableDistortion = " << (c.m_enableDistortion ? "true" : "false") << ";\n";
    o << "    bool animate = " << (c.m_animate ? "true" : "false") << ";\n";
    o << "    int effectPreset = " << c.m_effectPreset << ";\n";
    o << "    int blendMode = " << c.m_blendMode << ";\n";
    o << "    int noiseType = " << c.m_noiseType << ";\n";
    o << "};\n\n";

    o << "class ShaderController {\n";
    o << "public:\n";
    o << "    void compile(const char* vs, const char* fs);\n";
    o << "    void applyUniforms(unsigned int program, const ShaderConfig& cfg, float timeSec, float resX, float resY);\n";
    o << "    void update(float deltaTime);\n";
    o << "private:\n";
    o << "    float m_elapsed{0.0f};\n";
    o << "};\n\n";
    o << "} // namespace acs_export\n\n";

    o << ShaderConverter::wrapAsCppRawStringLiterals(state.m_vertexSource, state.m_fragmentSource);
    return o.str();
}

} // namespace acs
